### ISSUE TITLE
Agent could be updated with getIdentity() result

### ISSUE THREAD

**Issue by van-ibm** [IBM-Blockchain-Identity/openssi-websdk#3]
If you construct an agent

`new Agent(accountUrl, holderName, holderPassword);`

You get back the agent instance, which has properties set such as `url`.  The `url` is actually the account URL and not the agent's URL.  This could be confusing.

Additionally, calling `agent.getIdentity()` returns additional data about the agent. The `url` for example in this result is the expected agent's URL.

It seems to me more natural to internally update the agent's properties with the result of the `getIdentity` function.  This would properly update the agent's URL for one.  But it also alleviates me from having a var that is the result of the constructor and another var that is the result of the `getIdentity` call.  Semantically both vars are the "agent", correct?  So does it make more sense for the `getIdentity` to act more like an `init`?

**Comment by masterDev1985** [comment]
The `url` property of the `Agent` instance should really only be used to form HTTP requests to the cloud agent in the agent's `request()` calls.  In my opinion, we shouldn't set the expectation that the properties on the `Agent` instances will have up-to-date information on the cloud agent; developers should be writing their code around the format of the objects returned by the cloud agent API through the `getIdentity()` method instead.  This protects the SDK from needing as many new releases whenever the cloud agent changes the shape of the objects returned by the API.

Also, I try to avoid having `init` methods when I can.  It complicates code by having to account for both the initialized and uninitialized states of the object in all of its methods.  If we did go down this route, I'd avoid exposing the `Agent` class and instead expose an `AgentFactory` that constructs and initializes the `Agent` objects for the developer in order to avoid the github issues that would be posted by a developer trying to use an uninitialized `Agent`.

**Comment by masterDev1985** [comment]
That being said, I appreciate the feedback on the structure of the SDK.  The outside perspective helps catch design flaws.  Thanks @van-ibm

**Comment by van-ibm** [comment]
That makes sense (encapsulating such properties).  I had started writing test cases that was doing checks of the agent URLs to verify they were indeed connected.  Most developers won't have such a concern.  I later re-wrote tests to check the pairwise DIDs, which I suppose is the more SSI-like way to verify the connection details.

The sample connection offer in the README uses the `url` property.  Should we then perhaps use `name` or `did` to further remove awareness/reliance on `url`?
